// ima-frontend-react/src/components/NewApplicationComponent.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { createApplication } from '../services/ApplicationService';
import { listInternships } from '../services/InternshipService';
import { listStudents } from '../services/StudentService';

const NewApplicationComponent = () => {
    const navigator = useNavigate();
    
    const [internships, setInternships] = useState([]);
    const [students, setStudents] = useState([]);
    const [isSubmitting, setIsSubmitting] = useState(false);
    
    // Nouvel état pour stocker le fichier binaire PDF
    const [cvFile, setCvFile] = useState(null);

    const [newApplication, setNewApplication] = useState({
        applicationDate: new Date().toISOString().split('T')[0],
        status: 'PENDING',
        coverLetter: '',
        internshipId: '', // Simplifié pour faciliter le mapping avant envoi
        studentId: ''
    });

    useEffect(() => {
        // Appels API pour remplir les listes (à décommenter selon vos services)
        listInternships().then(res => setInternships(res.data));
        listStudents().then(res => setStudents(res.data));
    }, []);

    const handleChange = (e) => {
        const { name, value } = e.target;
        setNewApplication({ ...newApplication, [name]: value });
    };

    // Gestion spécifique pour le fichier
    const handleFileChange = (e) => {
        setCvFile(e.target.files[0]);
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        
        if (!cvFile) {
            alert("Veuillez sélectionner un fichier PDF pour le CV.");
            return;
        }

        setIsSubmitting(true);

        try {
            // On prépare l'objet JSON attendu par le Backend (ApplicationRequest)
            const applicationRequest = {
                applicationDate: newApplication.applicationDate,
                status: newApplication.status,
                coverLetter: newApplication.coverLetter,
                internshipId: newApplication.internshipId,
                studentId: newApplication.studentId
            };

            // Appel au service corrigé (celui qui utilise FormData)
            await createApplication(applicationRequest, cvFile);
            
            navigator('/applications');
        } catch (error) {
            console.error(error);
            alert("Erreur lors de la création de la candidature.");
        }finally{
            setIsSubmitting(false);
        }
    };

    return (
        <div className="container mt-5">
            <div className="card shadow-lg border-0">
                <div className="card-header bg-success text-white">
                    <h3 className="mb-0">Nouvelle Candidature</h3>
                </div>
                <div className="card-body p-4">
                    <form onSubmit={handleSubmit}>
                        <div className="row">
                            <div className="col-md-6 mb-3">
                                <label className="form-label fw-bold">Étudiant</label>
                                <select name="studentId" className="form-select" onChange={handleChange} required>
                                    <option value="">Choisir un étudiant...</option>
                                    {students.map(st => <option key={st.id} value={st.id}>{st.lastName} {st.firstName}</option>)}
                                </select>
                            </div>

                            <div className="col-md-6 mb-3">
                                <label className="form-label fw-bold">Offre de Stage</label>
                                <select name="internshipId" className="form-select" onChange={handleChange} required>
                                    <option value="">Choisir un stage...</option>
                                    {internships.map(i => <option key={i.id} value={i.id}>{i.title}</option>)}
                                </select>
                            </div>

                            {/* Changement ici : type="file" au lieu de type="url" */}
                            <div className="col-md-6 mb-3">
                                <label className="form-label fw-bold">Document CV (PDF)</label>
                                <input 
                                    type="file" 
                                    name="cvFile" 
                                    className="form-control" 
                                    accept=".pdf" 
                                    onChange={handleFileChange} 
                                    required 
                                />
                            </div>

                            <div className="col-md-6 mb-3">
                                <label className="form-label fw-bold">Date de candidature</label>
                                <input type="date" name="applicationDate" className="form-control" value={newApplication.applicationDate} onChange={handleChange} required />
                            </div>

                            <div className="col-md-12 mb-3">
                                <label className="form-label fw-bold">Lettre de motivation</label>
                                <textarea name="coverLetter" className="form-control" rows="5" value={newApplication.coverLetter} onChange={handleChange} placeholder="Décrivez votre motivation..."></textarea>
                            </div>
                        </div>

                        <div className="d-flex justify-content-end mt-3">
                            <button type="button" className="btn btn-outline-secondary me-2" onClick={() => navigator(-1)}>Annuler

                            </button>
                            

                            <button type="submit" className="btn btn-success px-5" disabled={isSubmitting}>
                                {isSubmitting ? (
                                    <>
                                        <span className="spinner-border spinner-border-sm me-2"></span>
                                        Envoi en cours...
                                    </>
                                ) : "Soumettre la candidature"}
                            </button>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    );
};

export default NewApplicationComponent;

// ima-standalone/src/app/components/forms/application/new-application.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ApplicationService } from '../../../services/application/application-service';
import { InternshipService } from '../../../services/internship/internship-service';
import { StudentService } from '../../../services/student/student-service';
import { Router } from '@angular/router';
import { ApplicationRequest } from '../../../core/api/models';
import { CommonModule } from '@angular/common';


@Component({
  selector: 'app-new-application',
  imports: [
    CommonModule,
    ReactiveFormsModule,
  ],
  templateUrl: './new-application.component.html',
  styleUrl: './new-application.component.css',
})
export class NewApplicationComponent implements OnInit {

    applicationForm: FormGroup;
    internships: any[] = [];
    students: any[] = [];
    isSubmitting = false;
    cvFile: File | null = null;
    loading: boolean = false;

    constructor(
        private fb: FormBuilder,
        private applicationService: ApplicationService,
        private internshipService: InternshipService,
        private studentService: StudentService,
        private router: Router
    ) {
        // Initialisation du formulaire avec les valeurs par défaut de votre code React
        this.applicationForm = this.fb.group({
            applicationDate: [new Date().toISOString().split('T')[0], Validators.required],
            status: ['PENDING'],
            coverLetter: ['', Validators.required],
            internshipId: ['', Validators.required],
            studentId: ['', Validators.required]
        });
    }

    ngOnInit(): void {
        this.loadData();
    }

    loadData(): void {
        // Équivalent du useEffect pour charger les listes
        this.internshipService.getAllInternships().subscribe({
            next: async(response: any) =>{
                let data = response;

                // Si c'est un Blob, on doit le convertir en texte puis en JSON
                if (response instanceof Blob) {
                    const text = await response.text();
                    data = JSON.parse(text);
                }

                // Une fois converti, on applique la logique de vérification
                if (Array.isArray(data)) {
                    this.internships = data;
                } else if (data && Array.isArray(data.body)) {
                    this.internships = data.body;
                } else {
                    this.internships = [];
                }
                this.loading = false;

            } ,

            error: (err) => console.error("Erreur stages:", err)
        });

        this.studentService.getAllStudents().subscribe({
            next: async(response: any) => {
                let data = response;

                if(response instanceof Blob){
                    const text = await response.text();
                    data = JSON.parse(text);
                }

                if(Array.isArray(data)){
                    this.students = data;
                } else if(data && Array.isArray(data.body)){
                    this.students = data.body;
                } else {
                    this.students = [];
                }
                this.loading = false;

            },
            error: (err) => console.error("Erreur étudiants:", err)
        });
    }

    // Équivalent de handleFileChange
    onFileChange(event: any): void {
        if (event.target.files.length > 0) {
        this.cvFile = event.target.files[0];
        }
    }

    // Équivalent de handleSubmit
    onSubmit(): void {
        if (!this.cvFile) {
        alert("Veuillez sélectionner un fichier PDF pour le CV.");
        return;
        }

        if (this.applicationForm.invalid) {
        this.applicationForm.markAllAsTouched();
        return;
        }

        this.isSubmitting = true;

        const formValue = this.applicationForm.value;

        /** * Mapping vers l'interface ApplicationRequest (OpenAPI)
         * Note: Selon votre interface définie plus haut, nous n'incluons que les champs connus.
         */
        const applicationRequest: ApplicationRequest = {
        coverLetter: formValue.coverLetter,
        internshipId: Number(formValue.internshipId),
        cvUrl: this.cvFile.name // Requis par votre interface Request
        };

        // Appel au service createApplicationWithCv (Multipart)
        this.applicationService.createApplicationWithCv(applicationRequest, this.cvFile).subscribe({
        next: () => {
            this.router.navigate(['/applications']);
        },
        error: (error) => {
            console.error("Erreur détaillée:", error);
            alert("Erreur lors de la création de la candidature.");
            this.isSubmitting = false;
        }
        });
    }

    cancel(){
        this.router.navigate(['/applications']);
    }
}


<div class="container mt-5">
    <div class="card shadow-lg border-0">
        <div class="card-header bg-success text-white">
            <h3 class="mb-0">Nouvelle Candidature</h3>
        </div>
        <div class="card-body p-4">
            <form [formGroup]="applicationForm" (ngSubmit)="onSubmit()">
                <div class="row">

                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold">Étudiant</label>
                        <select formControlName="studentId" class="form-select"
                                [class.is-invalid]="applicationForm.get('studentId')?.touched && applicationForm.get('studentId')?.invalid">
                        <option value="">Choisir un étudiant...</option>
                        <option *ngFor="let st of students" [value]="st.id">
                            {{ st.lastName }} {{ st.firstName }}
                        </option>
                        </select>
                    </div>

                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold">Offre de Stage</label>
                        <select formControlName="internshipId" class="form-select"
                                [class.is-invalid]="applicationForm.get('internshipId')?.touched && applicationForm.get('internshipId')?.invalid">
                        <option value="">Choisir un stage...</option>
                        <option *ngFor="let i of internships" [value]="i.id">
                            {{ i.title }}
                        </option>
                        </select>
                    </div>

                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold">Document CV (PDF)</label>
                        <input type="file" class="form-control" accept=".pdf"
                            (change)="onFileChange($event)" required>
                        <div *ngIf="applicationForm.touched && ! cvFile" class="text-danger small mt-1">
                        Le fichier PDF est requis.
                        </div>
                    </div>

                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold">Date de candidature</label>
                        <input type="date" formControlName="applicationDate" class="form-control"
                            [class.is-invalid]="applicationForm.get('applicationDate')?.touched && applicationForm.get('applicationDate')?.invalid">
                    </div>

                    <div class="col-md-12 mb-3">
                        <label class="form-label fw-bold">Lettre de motivation</label>
                        <textarea formControlName="coverLetter" class="form-control" rows="5"
                                placeholder="Décrivez votre motivation..."></textarea>
                    </div>
                </div>

                <div class="d-flex justify-content-end mt-3">
                    <button type="button" class="btn btn-outline-secondary me-2" (click)="cancel()">
                        Annuler
                    </button>

                    <button type="submit" class="btn btn-success px-5" [disabled]="isSubmitting">
                        <span *ngIf="isSubmitting" class="spinner-border spinner-border-sm me-2"></span>
                        {{ isSubmitting ? 'Envoi en cours...' : 'Soumettre la candidature' }}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
