// ima-standalone/src/app/components/forms/agreement/new-agreement.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { AgreementService } from '../../../services/agreement/agreement-service';
import { TeacherService } from '../../../services/teacher/teacher-service';
import { ApplicationService } from '../../../services/application/application-service';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-new-agreement',
  imports: [
    CommonModule,
    ReactiveFormsModule,

  ],
  templateUrl: './new-agreement.component.html',
  styleUrl: './new-agreement.component.css',
})
export class NewAgreementComponent implements OnInit {
    agreementForm: FormGroup;
    teachers: any[] = [];
    applications: any[] = [];
    isSubmitting = false;

    constructor(
        private fb: FormBuilder,
        private agreementService: AgreementService,
        private teacherService: TeacherService,
        private applicationService: ApplicationService,
        private router: Router
    ) {
        // Initialisation du formulaire réactif
        this.agreementForm = this.fb.group({
        selectedAppId: ['', Validators.required],
        startDate: ['', Validators.required],
        endDate: ['', Validators.required],
        validatorId: ['', Validators.required],
        status: ['DRAFT'],
        documentPdfUrl: ['']
        });
    }

    ngOnInit(): void {
        this.loadInitialData();
    }

    loadInitialData(): void {
        // Chargement des enseignants
        this.teacherService.getAllTeachers().subscribe({
            next: async(response) => {
                let data = response;

                if(response instanceof Blob){
                    const text = await response.text();
                    data = JSON.parse(text);
                }

                // Une fois converti, on applique la logique de vérification
                if (Array.isArray(data)) {
                    this.teachers = data;
                } else {
                    this.teachers = [];
                }

            },
            error: (err) => console.error("Erreur enseignants", err)
        });

        // Chargement des candidatures
        this.applicationService.getAllApplications().subscribe({
            next: async(response) => {
                let data = response;

                if(response instanceof Blob){
                    const text = await response.text();
                    data = JSON.parse(text);
                }

                // Une fois converti, on applique la logique de vérification
                if (Array.isArray(data)) {
                    this.applications = data;
                } else {
                    this.applications = [];
                }

            },
            error: (err) => console.error("Erreur candidatures", err)
        });
    }

    onSubmit(): void {
        if (this.agreementForm.invalid) {
        this.agreementForm.markAllAsTouched();
        return;
        }

        this.isSubmitting = true;
        const { selectedAppId, ...agreementData } = this.agreementForm.value;

        // Appel au service avec l'ID de candidature et les données de convention
        this.agreementService.createAgreement(selectedAppId, agreementData).subscribe({
        next: () => {
            this.router.navigate(['/agreements']);
        },
        error: (error) => {
            console.error("Erreur création convention", error);
            alert("Erreur lors de la création de la convention.");
            this.isSubmitting = false;
        }
        });
    }

    goBack(): void {
        window.history.back();
    }
}

<div class="container mt-5">
    <div class="card shadow-lg border-0">
        <div class="card-header bg-dark text-white text-center py-3">
            <h3 class="mb-0">Génération de Convention</h3>
        </div>
        <div class="card-body p-4">
            <form [formGroup]="agreementForm" (ngSubmit)="onSubmit()">
                <div class="row">

                    <div class="col-md-12 mb-3">
                        <label class="form-label fw-bold text-primary">Candidature concernée</label>
                        <select
                        formControlName="selectedAppId"
                        class="form-select border-primary"
                        [class.is-invalid]="agreementForm.get('selectedAppId')?.touched && agreementForm.get('selectedAppId')?.invalid">
                            <option value="">-- Choisir la candidature --</option>
                            <option *ngFor="let app of applications" [value]="app.id">
                                ID: {{app.id}} - {{app.internshipTitle}} ({{app.studentName}})
                            </option>
                        </select>
                        <div class="invalid-feedback">Veuillez sélectionner une candidature.</div>
                    </div>

                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold">Date de début du stage</label>
                        <input type="date" formControlName="startDate" class="form-control"
                            [class.is-invalid]="agreementForm.get('startDate')?.touched && agreementForm.get('startDate')?.invalid">
                    </div>

                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold">Date de fin du stage</label>
                        <input type="date" formControlName="endDate" class="form-control"
                            [class.is-invalid]="agreementForm.get('endDate')?.touched && agreementForm.get('endDate')?.invalid">
                    </div>

                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold">Enseignant Validateur</label>
                        <select formControlName="validatorId" class="form-select"
                                [class.is-invalid]="agreementForm.get('validatorId')?.touched && agreementForm.get('validatorId')?.invalid">
                            <option value="">-- Sélectionner un enseignant --</option>
                            <option *ngFor="let t of teachers" [value]="t.id">
                                {{t.firstName}} {{t.lastName}}
                            </option>
                        </select>
                    </div>

                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold">Statut Initial</label>
                        <select formControlName="status" class="form-select">
                            <option value="DRAFT">Brouillon (DRAFT)</option>
                            <option value="PENDING_VALIDATION">En attente de validation</option>
                            <option value="VALIDATED">Validée par l'enseignant</option>
                            <option value="SENT_FOR_SIGNATURE">Envoyée pour signature</option>
                            <option value="SIGNED">Convention Signée</option>
                            <option value="CANCELED">Convention Annulée</option>
                        </select>
                    </div>
                </div>

                <div class="d-flex justify-content-between mt-4">
                    <button type="button" class="btn btn-outline-secondary" (click)="goBack()">
                        Retour
                    </button>
                    <button type="submit" class="btn btn-primary px-5" [disabled]="isSubmitting">
                        <span *ngIf="isSubmitting" class="spinner-border spinner-border-sm me-2"></span>
                        {{ isSubmitting ? 'Création...' : 'Créer la Convention' }}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

// ima-frontend-react/src/components/NewAgreementComponent.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { createAgreement } from '../services/AgreementService';
import { listTeachers } from '../services/TeacherService';
import { listApplications } from '../services/ApplicationService';

const NewAgreementComponent = () => {
    const navigate = useNavigate();
    
    // États pour les listes déroulantes
    const [teachers, setTeachers] = useState([]);
    const [applications, setApplications] = useState([]); // Ajouté
    
    // États pour la sélection
    const [selectedAppId, setSelectedAppId] = useState('');
    const [isSubmitting, setIsSubmitting] = useState(false);

    const [agreement, setAgreement] = useState({
        startDate: '',
        endDate: '',
        status: 'DRAFT',
        validatorId: '',
        documentPdfUrl: ''
    });
    
    useEffect(() => {
        // Charger les enseignants
        listTeachers().then(res => setTeachers(res.data));
        // Charger les candidatures pour obtenir l'applicationId
        listApplications().then(res => setApplications(res.data));
    }, []);

    const handleChange = (e) => {
        const { name, value } = e.target;
        setAgreement({ ...agreement, [name]: value });
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!selectedAppId) {
            alert("Veuillez sélectionner une candidature.");
            return;
        }
        
        setIsSubmitting(true);
        try {
            // On envoie enfin un ID valide au lieu de undefined
            await createAgreement(selectedAppId, agreement);
            navigate('/agreements');
        } catch (error) {
            console.error("Erreur création convention", error);
            alert("Erreur lors de la création de la convention.");
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <div className="container mt-5">
            <div className="card shadow-lg border-0">
                <div className="card-header bg-dark text-white text-center">
                    <h3 className="mb-0">Génération de Convention</h3>
                </div>
                <div className="card-body p-4">
                    <form onSubmit={handleSubmit}>
                        <div className="row">
                            {/* --- AJOUT DU SÉLECTEUR D'APPLICATION (Résout l'erreur 400/401) --- */}
                            <div className="col-md-12 mb-3">
                                <label className="form-label fw-bold text-primary">Candidature concernée</label>
                                <select 
                                    className="form-select border-primary" 
                                    value={selectedAppId} 
                                    onChange={(e) => setSelectedAppId(e.target.value)} 
                                    required
                                >
                                    <option value="">-- Choisir la candidature --</option>
                                    {applications.map(app => (
                                        <option key={app.id} value={app.id}>
                                            ID: {app.id} - {app.internshipTitle} ({app.studentName})
                                        </option>
                                    ))}
                                </select>
                            </div>

                            <div className="col-md-6 mb-3">
                                <label className="form-label fw-bold">Date de début du stage</label>
                                <input type="date" name="startDate" className="form-control" 
                                    value={agreement.startDate} onChange={handleChange} required />
                            </div>

                            <div className="col-md-6 mb-3">
                                <label className="form-label fw-bold">Date de fin du stage</label>
                                <input type="date" name="endDate" className="form-control" 
                                    value={agreement.endDate} onChange={handleChange} required />
                            </div>

                            <div className="col-md-6 mb-3">
                                <label className="form-label fw-bold">Enseignant Validateur</label>
                                <select name="validatorId" className="form-select" 
                                    value={agreement.validatorId} onChange={handleChange} required>
                                    <option value="">-- Sélectionner un enseignant --</option>
                                    {teachers.map(t => (
                                        <option key={t.id} value={t.id}>{t.firstName} {t.lastName}</option>
                                    ))}
                                </select>
                            </div>

                            <div className="col-md-6 mb-3">
                                <label className="form-label fw-bold">Statut Initial</label>
                                <select name="status" className="form-select" 
                                    value={agreement.status} onChange={handleChange}>
                                    <option value="DRAFT">Brouillon (DRAFT)</option>
                                    <option value="PENDING_VALIDATION">En attente de validation</option>
                                    <option value="VALIDATED">Validée par l'enseignant </option>
                                    <option value="SENT_FOR_SIGNATURE">Envoyée aux parties pour signature </option>
                                    <option value="SIGNED">Convention Signée </option>
                                    <option value="CANCELED">Convention Annulée </option>
                                    
                                </select>
                            </div>
                        </div>

                        <div className="d-flex justify-content-between mt-4">
                            <button type="button" className="btn btn-outline-secondary" onClick={() => navigate(-1)}>
                                Retour
                            </button>
                            <button type="submit" className="btn btn-primary px-5" disabled={isSubmitting}>
                                {isSubmitting ? <span className="spinner-border spinner-border-sm"></span> : "Créer la Convention"}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    );
};

export default NewAgreementComponent;
