// ima-standalone/src/app/components/forms/company/new-company.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { CompanyService } from '../../../services/company/company-service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-new-company.component',
  imports: [
    CommonModule,
    ReactiveFormsModule,
  ],
  templateUrl: './new-company.component.html',
  styleUrl: './new-company.component.css',
})
export class NewCompanyComponent implements OnInit {
    companyForm: FormGroup;
    id: string | null = null;
    userId: string | null = null;
    loading = false;

    constructor(
        private fb: FormBuilder,
        private route: ActivatedRoute,
        public router: Router,
        private companyService: CompanyService
    ) {
        // Définition du formulaire avec validations natives Angular
        this.companyForm = this.fb.group({
        name: ['', Validators.required],
        address: ['', Validators.required],
        description: ['', Validators.required],
        website: ['', [Validators.required, Validators.pattern('https?://.+')]],
        phone: ['', Validators.required],
        professionalEmail: ['', [Validators.required, Validators.email]],
        userId: ['']
        });
    }

    ngOnInit(): void {
        this.id = this.route.snapshot.paramMap.get('id');
        this.userId = this.route.snapshot.paramMap.get('userId');

        if (this.userId) {
        this.companyForm.patchValue({ userId: this.userId });
        }

        if (this.id) {
        this.loadCompany();
        }
    }

    loadCompany(): void {
        this.loading = true;
        this.companyService.getCompanyById(Number(this.id)).subscribe({
        next: async(response: any) => {
            let data = response;

            if(response instanceof Blob){
                const text = await response.text();
                data = JSON.parse(text);
            }

            this.companyForm.patchValue(data);
            // On s'assure que le userId de l'URL reste prioritaire si nécessaire
            if (this.userId) this.companyForm.patchValue({ userId: this.userId });
            this.loading = false;
        },
        error: (err) => {
            console.error("Erreur de chargement", err);
            alert("Impossible de récupérer les données de l'entreprise.");
            this.loading = false;
        }
        });
    }

    onSubmit(): void {
        if (this.companyForm.invalid) {
        this.companyForm.markAllAsTouched();
        return;
        }

        this.loading = true;
        const payload = this.companyForm.value;

        if (this.id) {
        this.companyService.updateCompany(Number(this.id), payload).subscribe({
            next: () => this.handleSuccess(),
            error: (err) => this.handleError(err)
        });
        } else {
        if (!this.userId) {
            alert("ID Utilisateur manquant pour la création.");
            this.loading = false;
            return;
        }
        this.companyService.createCompany(Number(this.userId), payload).subscribe({
            next: () => this.handleSuccess(),
            error: (err) => this.handleError(err)
        });
        }
    }

    private handleSuccess() {
        this.loading = false;
        this.router.navigate(['/companies']);
    }

    private handleError(err: any) {
        this.loading = false;
        const serverMsg = err.error?.message || "Une erreur est survenue.";
        alert(serverMsg);
    }
}


<div class="container my-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white text-center">
                    <h2 class="mb-0">
                        {{ id ? "Modifier l'entreprise" : "Nouvelle Entreprise" }}
                    </h2>
                </div>

                <div *ngIf="userId && !id" class="alert alert-info m-3 mb-0">
                    Création d'un profil entreprise pour l'utilisateur ID : <strong>{{ userId }}</strong>
                </div>

                <div *ngIf="loading && id" class="text-center my-5">
                    <div class="spinner-border text-primary" role="status"></div>
                    <p class="mt-2">Chargement des données...</p>
                </div>

                <div class="card-body p-4" *ngIf="!(loading && id)">
                    <form [formGroup]="companyForm" (ngSubmit)="onSubmit()">

                        <div class="mb-3">
                            <label class="form-label fw-bold">Nom de l'entreprise</label>
                            <input type="text" class="form-control" formControlName="name"
                                [class.is-invalid]="companyForm.get('name')?.touched && companyForm.get('name')?.invalid">
                            <div class="invalid-feedback">Le nom est obligatoire</div>
                        </div>

                        <div class="mb-3">
                            <label class="form-label fw-bold">Adresse</label>
                            <input type="text" class="form-control" formControlName="address"
                                [class.is-invalid]="companyForm.get('address')?.touched && companyForm.get('address')?.invalid">
                            <div class="invalid-feedback">L'adresse est obligatoire</div>
                        </div>

                        <div class="mb-3">
                            <label class="form-label fw-bold">Description</label>
                            <textarea class="form-control" formControlName="description" rows="3"
                                [class.is-invalid]="companyForm.get('description')?.touched && companyForm.get('description')?.invalid"></textarea>
                            <div class="invalid-feedback">La description est obligatoire</div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label class="form-label fw-bold">Site Web</label>
                                <input type="text" class="form-control" formControlName="website" placeholder="https://..."
                                [class.is-invalid]="companyForm.get('website')?.touched && companyForm.get('website')?.invalid">
                                <div class="invalid-feedback">L'URL doit être valide (ex: https://...)</div>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="form-label fw-bold">Téléphone</label>
                                <input type="tel" class="form-control" formControlName="phone"
                                [class.is-invalid]="companyForm.get('phone')?.touched && companyForm.get('phone')?.invalid">
                                <div class="invalid-feedback">Le numéro est obligatoire</div>
                            </div>
                        </div>

                        <div class="mb-4">
                            <label class="form-label fw-bold">Email Professionnel</label>
                            <input type="email" class="form-control" formControlName="professionalEmail"
                                [class.is-invalid]="companyForm.get('professionalEmail')?.touched && companyForm.get('professionalEmail')?.invalid">
                            <div class="invalid-feedback">Veuillez entrer un email professionnel valide</div>
                        </div>

                        <div class="d-flex justify-content-end gap-2">
                            <button type="button" class="btn btn-light border" (click)="router.navigate(['/companies'])">
                                Annuler
                            </button>
                            <button type="submit" class="btn btn-success" [disabled]="loading">
                                <span *ngIf="loading" class="spinner-border spinner-border-sm me-1"></span>
                                {{ loading ? "En cours..." : (id ? "Mettre à jour" : "Créer l'entreprise") }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

// ima-frontend-react/src/components/NewCompanyComponent.jsx
import React, { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom';
import { createCompany, getCompany, updateCompany } from '../services/CompanyService';

const NewCompanyComponent = () => {

    const { id, userId } = useParams();

    const [newCompany, setNewCompany] = useState({       
        name: "",
        address: "",
        description: "",
        website: "",
        phone: "",
        professionalEmail: "",
        userId: userId || ""
    });

    const navigator = useNavigate();

    const [loading, setLoading] = useState(false);
    const [errors, setErrors] = useState({});

    // 1. Chargement des données en mode Edition
    useEffect(() => {
        if (!id) return;

        const fetchCompany = async () => {
            try {
                setLoading(true);
                const response = await getCompany(id);
                const data = response.data;

                setNewCompany({
                    name: data.name || "",
                    address: data.address || "",
                    description: data.description || "",
                    website: data.website || "",
                    phone: data.phone || "",
                    professionalEmail: data.professionalEmail || "",
                    userId: userId || data.userId || ""
                });
            } catch (error) {
                console.error("Erreur lors du chargement :", error);
                alert("Impossible de récupérer les données de l'entreprise.");
            } finally {
                setLoading(false);
            }
        };

        fetchCompany();
    }, [id, userId]);

    const handleChange = (e) => {
        const { name, value } = e.target;
        setNewCompany(prev => ({ ...prev, [name]: value }));
        // Nettoyage de l'erreur en temps réel
        if (errors[name]) setErrors(prev => ({ ...prev, [name]: "" }));
    };

    // 2. Validation du formulaire
    const validateForm = () => {
        const newErrors = {};
        if (!newCompany.name.trim()) newErrors.name = "Le nom est obligatoire";
        if (!newCompany.address.trim()) newErrors.address = "L'adresse est obligatoire";
        if (!newCompany.description.trim()) newErrors.description = "La description est obligatoire";
        
        const emailRegex = /^\S+@\S+\.\S+$/;
        if (!emailRegex.test(newCompany.professionalEmail)) {
            newErrors.professionalEmail = "Email professionnel invalide";
        }

        const urlRegex = /^https?:\/\/.+/;
        if (!urlRegex.test(newCompany.website)) {
            newErrors.website = "L'URL doit commencer par http:// ou https://";
        }

        if (!newCompany.phone.trim()) newErrors.phone = "Le numéro de téléphone est obligatoire";

        setErrors(newErrors);
        return Object.keys(newErrors).length === 0;
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        if(!validateForm()) return;

        try {
            setLoading(true);
            if(id) {
                await updateCompany(id, newCompany);
                console.log('Company mis à jour');
                navigator('/companies');
            }else{
                if (!userId) {
                    alert("ID Utilisateur manquant pour la création.");
                    return;
                }
                await createCompany(userId, newCompany);
                console.log('Company créé')
                navigator('/companies');
            }
        }catch (error){
            console.error('Erreur lors de la sauvegarde :', error);
            const serverMsg = error.response?.data?.message || "Une erreur est survenue.";
            alert(serverMsg);
        }finally {
            setLoading(false);
        }
    };

    if (loading && id) return <div className="text-center my-5">Chargement des données...</div>;

    return (
        <div className='container my-4'>
            <div className="row justify-content-center">
                <div className="col-md-8">
                    <div className="card shadow-sm">
                        <div className="card-header bg-primary text-white text-center">
                            <h2 className="mb-0">{id ? "Modifier l'entreprise" : "Nouvelle Entreprise"}</h2>
                        </div>

                        {userId && !id && (
                            <div className="alert alert-info">
                                Création d'un profil entreprise pour l'utilisateur ID : <strong>{userId}</strong>
                            </div>
                        )}
                        
                        <div className="card-body p-4">
                            <form onSubmit={handleSubmit}>
                                <div className="mb-3">
                                    <label className="form-label fw-bold">Nom de l'entreprise</label>
                                    <input
                                        type="text"
                                        className={`form-control ${errors.name ? 'is-invalid' : ''}`}
                                        name="name"
                                        value={newCompany.name}
                                        onChange={handleChange}
                                    />
                                    <div className="invalid-feedback">{errors.name}</div>
                                </div>

                                <div className="mb-3">
                                    <label className="form-label fw-bold">Adresse</label>
                                    <input
                                        type="text"
                                        className={`form-control ${errors.address ? 'is-invalid' : ''}`}
                                        name="address"
                                        value={newCompany.address}
                                        onChange={handleChange}
                                    />
                                    <div className="invalid-feedback">{errors.address}</div>
                                </div>

                                <div className="mb-3">
                                    <label className="form-label fw-bold">Description</label>
                                    <textarea
                                        className={`form-control ${errors.description ? 'is-invalid' : ''}`}
                                        name="description"
                                        rows="3"
                                        value={newCompany.description}
                                        onChange={handleChange}
                                    />
                                    <div className="invalid-feedback">{errors.description}</div>
                                </div>

                                <div className="row">
                                    <div className="col-md-6 mb-3">
                                        <label className="form-label fw-bold">Site Web</label>
                                        <input
                                            type="text"
                                            className={`form-control ${errors.website ? 'is-invalid' : ''}`}
                                            name="website"
                                            placeholder="https://..."
                                            value={newCompany.website}
                                            onChange={handleChange}
                                        />
                                        <div className="invalid-feedback">{errors.website}</div>
                                    </div>
                                    <div className="col-md-6 mb-3">
                                        <label className="form-label fw-bold">Téléphone</label>
                                        <input
                                            type="tel"
                                            className={`form-control ${errors.phone ? 'is-invalid' : ''}`}
                                            name="phone"
                                            value={newCompany.phone}
                                            onChange={handleChange}
                                        />
                                        <div className="invalid-feedback">{errors.phone}</div>
                                    </div>
                                </div>

                                <div className="mb-4">
                                    <label className="form-label fw-bold">Email Professionnel</label>
                                    <input
                                        type="email"
                                        className={`form-control ${errors.professionalEmail ? 'is-invalid' : ''}`}
                                        name="professionalEmail"
                                        value={newCompany.professionalEmail}
                                        onChange={handleChange}
                                    />
                                    <div className="invalid-feedback">{errors.professionalEmail}</div>
                                </div>

                                <div className="d-flex justify-content-end gap-2">
                                    <button type="button" className="btn btn-light border" onClick={() => navigator('/companies')}>
                                        Annuler
                                    </button>
                                    <button type="submit" className="btn btn-success" disabled={loading}>
                                        {loading ? "En cours..." : (id ? "Mettre à jour" : "Créer l'entreprise")}
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default NewCompanyComponent
