// ima-standalone/src/app/components/forms/message/new-message.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { MessageService } from '../../../services/message/message-service';
import { UserService } from '../../../services/user/user-service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-new-message.component',
  imports: [
    CommonModule,
    ReactiveFormsModule,
  ],
  templateUrl: './new-message.component.html',
  styleUrl: './new-message.component.css',
})
export class NewMessageComponent implements OnInit {

    @Output()
    messageCreated = new EventEmitter<void>();

    messageForm: FormGroup;
    users: any[] = [];
    loading = false;
    usersLoading = true;

    constructor(
        private fb: FormBuilder,
        private messageService: MessageService,
        private userService: UserService
    ){
        // Initialisation du formulaire (Équivalent des useState)
        this.messageForm = this.fb.group({
            recipientId: ['', Validators.required],
            content: ['', [Validators.required, Validators.minLength(1)]]
        });
    }

    ngOnInit(): void {
        this.fetchUsers();
    }

    fetchUsers(): void {
        this.usersLoading = true;
        this.userService.getAllUsers().subscribe({
            next: async(response: any) => {
                let userData = response.content || response || [];
                const currentUserId = Number(localStorage.getItem("userId"));

                if(response instanceof Blob){
                    const text = await response.text();
                    userData = JSON.parse(text);
                }

                // Filtrage et tri (Logique identique à votre useEffect)
                this.users = userData
                .filter((u: any) => u.id !== currentUserId)
                .sort((a: any, b: any) => a.lastName.localeCompare(b.lastName));

                this.usersLoading = false;
            },
            error: (err) => {
                console.error("Erreur chargement utilisateurs", err);
                this.users = [];
                this.usersLoading = false;
            }
        });
    }

    handleSubmit(): void {
        if(this.messageForm.invalid){
            return;
        }

        this.loading = true;
        const payload = {
            recipientId: parseInt(this.messageForm.value.recipientId),
            content: this.messageForm.value.content
        };

        this.messageService.createMessage(payload).subscribe({
            next: () => {
                this.messageForm.reset({ recipientId: '', content: '' });
                this.messageCreated.emit(); // Informe le parent
                this.loading = false;
            },
            error: (err) => {
                console.error("Erreur création:", err);
                this.loading = false;
            }
        });
    }

    // Helper pour formater les rôles (optionnel, pour garder le HTML propre)
    formatRoles(roles: any[]): string {
        if (!roles || roles.length === 0) return '';
        return ` (${roles.map(r => r.replace('ROLE_', '')).join(', ')})`;
    }

}


<p>new-message.component works!</p>
<div class="card shadow mb-4">
    <div class="card-header bg-success text-white">Nouveau Message</div>
    <div class="card-body">
        <form [formGroup]="messageForm" (ngSubmit)="handleSubmit()">

            <div class="mb-3">
                <label class="form-label small fw-bold">Destinataire</label>
                <select
                    class="form-select"
                    formControlName="recipientId"
                    [class.is-invalid]="messageForm.get('recipientId')?.touched && messageForm.get('recipientId')?.invalid"
                >
                    <option value="" disabled>
                        {{ usersLoading ? "Chargement des utilisateurs..." : "Sélectionnez un utilisateur..." }}
                    </option>
                    <option *ngFor="let user of users" [value]="user.id">
                        {{ (user.firstName && user.lastName) ? (user.firstName + ' ' + user.lastName) : user.email }}
                        {{ formatRoles(user.roles) }}
                    </option>
                </select>
            </div>

            <div class="mb-3">
                <label class="form-label small fw-bold">Message</label>
                <textarea
                    class="form-control"
                    rows="3"
                    formControlName="content"
                    [class.is-invalid]="messageForm.get('content')?.touched && messageForm.get('content')?.invalid"
                ></textarea>
            </div>

            <button type="submit" class="btn btn-success w-100" [disabled]="loading || messageForm.invalid">
                <span *ngIf="loading" class="spinner-border spinner-border-sm me-1"></span>
                {{ loading ? 'Envoi...' : 'Envoyer' }}
            </button>
        </form>
    </div>
</div>

// ima-frontend-react/src/components/NewMessageComponent.jsx
import React, { useEffect, useState } from 'react';
import { createMessage } from '../services/MessageService';
import { listUsers } from '../services/UserService';

const NewMessageComponent = ({ onMessageCreated }) => {
    
    const [users, setUsers] = useState([]);
    const [recipientId, setRecipientId] = useState('');
    const [content, setContent] = useState('');
    const [loading, setLoading] = useState(false);


    // Charger les utilisateurs au montage du composant
    useEffect(() => {
        const fetchUsers = async () => {
            try {
                const res = await listUsers();
                console.log("USERS RESPONSE =", res.data);

                const userData = res.data.content || res.data || []

                const currentUserId = Number(localStorage.getItem("userId"));

                const filteredAndSortedUsers = userData
                    .filter(u => u.id !== currentUserId)
                    .sort((a, b) =>
                        a.lastName.localeCompare(b.lastName)
                    );

                setUsers(filteredAndSortedUsers);

            } catch (error) {
                console.error("Erreur chargement utilisateurs", error);
                setUsers([]);
            }
        };

        fetchUsers();
    }, []);

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!recipientId || !content) return;

        setLoading(true);
        try {
            await createMessage({ 
                recipientId: parseInt(recipientId), 
                content 
            });
            setRecipientId('');
            setContent('');
            // Informe le parent qu'un nouveau message existe
            if (onMessageCreated) onMessageCreated();
        } catch (error) {
            console.error("Erreur création:", error);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="card shadow mb-4">
            <div className="card-header bg-success text-white">Nouveau Message</div>
            <div className="card-body">
                <form onSubmit={handleSubmit}>
                    <div className="mb-3">
                        <label className="form-label small fw-bold">Destinataire</label>
                        <select 
                            className="form-select" 
                            value={recipientId}
                            onChange={(e) => setRecipientId(e.target.value)}
                            required
                        >
                            <option value="">
                                {users.length === 0 ? "Chargement des utilisateurs..." : "Sélectionnez un utilisateur..."}
                            </option>
                            {users.map(user => (
                                <option key={user.id} value={user.id}>
                                    {user.firstName && user.lastName
                                        ? `${user.firstName} ${user.lastName}`
                                        : user.email}
                                    
                                    {/* Affichage des rôles entre parenthèses */}
                                    {user.roles && user.roles.length > 0 && 
                                        ` (${user.roles.map(r => r.replace('ROLE_', '')).join(', ')})`
                                    }
                                </option>
                            ))}
                        </select>
                    </div>
                    <div className="mb-3">
                        <label className="form-label small fw-bold">Message</label>
                        <textarea 
                            className="form-control" 
                            rows="3"
                            value={content}
                            onChange={(e) => setContent(e.target.value)}
                            required
                        />
                    </div>
                    <button type="submit" className="btn btn-success w-100" disabled={loading}   >
                        {loading ? 'Envoi...' : 'Envoyer'}
                    </button>
                </form>
            </div>
        </div>
    );
};

export default NewMessageComponent;
