// ima-standalone/src/app/components/forms/student/new-student.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { StudentService } from '../../../services/student/student-service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-new-student.component',
  imports: [
    CommonModule,
    ReactiveFormsModule,
  ],
  templateUrl: './new-student.component.html',
  styleUrl: './new-student.component.css',
})
export class NewStudentComponent implements OnInit {
    studentForm: FormGroup;
    id: string | null = null;
    userId: string | null = null;
    loading = false;

    constructor(
        private fb: FormBuilder,
        private route: ActivatedRoute,
        public router: Router,
        private studentService: StudentService
    ) {
        this.studentForm = this.fb.group({
        studentCode: ['', Validators.required],
        level: ['', Validators.required],
        userId: ['']
        });
    }

    ngOnInit(): void {
        // Récupération des paramètres (ex: /students/new/12 ou /students/edit/5)
        this.id = this.route.snapshot.paramMap.get('id');
        this.userId = this.route.snapshot.paramMap.get('userId');

        if (this.userId) {
            this.studentForm.patchValue({ userId: this.userId });
        }

        if (this.id) {
            //this.studentForm.get('studentCode')?.disable(); // Empêche la modification du code
            this.loadStudent();
        }
    }

    loadStudent(): void {
        if (!this.id) return; // Sécurité si l'ID est null

        this.loading = true;
        this.studentService.getStudentById(Number(this.id)).subscribe({
            next: async(response: any) => {
                let data = response;

                if(response instanceof Blob){
                    const text = await response.text();
                    data = JSON.parse(text);
                }
                // Remplissage automatique :
                // Angular cherche 'studentCode' et 'level' dans 'data'
                // et les place dans les inputs correspondants.
                this.studentForm.patchValue({
                    studentCode: data.studentCode,
                    level: data.level,
                    userId: data.userId || this.userId
                });
                console.log(data);
                this.loading = false;
            },
            error: (err) => {
                console.error("Erreur chargement étudiant", err);
                this.loading = false;
            }
        });
    }

    onSubmit(): void {
        if (this.studentForm.invalid) {
        this.studentForm.markAllAsTouched();
        return;
        }

        this.loading = true;
        const payload = this.studentForm.value;

        if (this.id) {
        // UPDATE
        this.studentService.updateStudent(Number(this.id), payload).subscribe({
            next: () => this.navigateToList(),
            error: (err) => this.handleError(err)
        });
        } else {
        // CREATE
        if (!this.userId) {
            alert("ID Utilisateur manquant.");
            this.loading = false;
            return;
        }
        this.studentService.createStudent(Number(this.userId), payload).subscribe({
            next: () => this.navigateToList(),
            error: (err) => this.handleError(err)
        });
        }
    }

    private navigateToList() {
        this.loading = false;
        this.router.navigate(['/students']);
    }

    private handleError(err: any) {
        this.loading = false;
        console.error('Erreur :', err);
        alert("Une erreur est survenue lors de l'enregistrement.");
    }
}

<div class="container my-4">
    <h2 class="text-center mb-4">
        {{ id ? "Modifier l'étudiant" : "Créer un nouvel étudiant" }}
    </h2>

    <div *ngIf="userId && !id" class="alert alert-info shadow-sm">
        Création d'un profil étudiant pour l'utilisateur ID : <strong>{{ userId }}</strong>
    </div>

    <div *ngIf="loading && id" class="text-center my-5">
        <div class="spinner-border text-primary" role="status"></div>
        <p class="mt-2">Chargement....</p>
    </div>

    <form *ngIf="!(loading && id)"
        [formGroup]="studentForm" (ngSubmit)="onSubmit()" class="border p-4 rounded shadow-sm bg-light"
        >
        <div class="row">
            <div class="col-md-6 mb-3">
                <label class="form-label">Code Étudiant</label>
                <input type="text" class="form-control" formControlName="studentCode"
                    [class.is-invalid]="studentForm.get('studentCode')?.touched && studentForm.get('studentCode')?.invalid">
                <div class="invalid-feedback">Le matricule est obligatoire</div>
            </div>

            <div class="col-md-6 mb-3">
                <label class="form-label">Niveau (Level)</label>
                <input type="text" class="form-control" formControlName="level"
                    [class.is-invalid]="studentForm.get('level')?.touched && studentForm.get('level')?.invalid">
                <div class="invalid-feedback">Le niveau d'étude est obligatoire</div>
            </div>
        </div>

        <div class="d-flex justify-content-end gap-2 mt-3">
            <button type="button" (click)="router.navigate(['/students'])" class="btn btn-outline-secondary">
                Annuler
            </button>
            <button type="submit" class="btn btn-primary" [disabled]="loading">
                <span *ngIf="loading" class="spinner-border spinner-border-sm me-1"></span>
                {{ loading ? "En cours..." : (id ? "Enregistrer" : "Créer") }}
            </button>
        </div>
    </form>
</div>

// ima-frontend-react/src/components/NewStudentComponent.jsx
import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { createStudent, getStudent, updateStudent } from '../services/StudentService';

const NewStudentComponent = () => {
    const { id, userId } = useParams();
    const navigator = useNavigate();

    const [newStudent, setNewStudent] = useState({
        studentCode: "",
        level: "",
        userId: userId || ""
    });

    const [loading, setLoading] = useState(false);
    const [errors, setErrors] = useState({});

    useEffect(() => {
        if (!id) return;

        const fetchStudent = async () => {
            try {
                setLoading(true);
                const response = await getStudent(id);
                const data = response.data;

                setNewStudent({
                    studentCode: data.studentCode || "",
                    level: data.level || "",
                    // On garde le userId de l'URL s'il est présent, sinon celui de la DB
                    userId: userId || data.userId || ""
                });
            } catch (error) {
                console.error("Erreur chargement etudiant", error);
                alert("Impossible de charger les données de l'étudiant.");
            } finally {
                setLoading(false);
            }
        };

        fetchStudent();
    }, [id, userId]); // Ajout de userId dans les dépendances

    const handleChange = (e) => {
        const { name, value } = e.target;
        setNewStudent(prev => ({ ...prev, [name]: value }));
        // Nettoyer l'erreur dès que l'utilisateur commence à écrire
        if (errors[name]) {
            setErrors(prev => ({ ...prev, [name]: null }));
        }
    };

    const validateForm = () => {
        const validationErrors = {};
        if (!newStudent.studentCode.trim()) validationErrors.studentCode = 'Le matricule est obligatoire';
        if (!newStudent.level.trim()) validationErrors.level = "Le niveau d'étude est obligatoire";
        
        setErrors(validationErrors);
        return Object.keys(validationErrors).length === 0;
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!validateForm()) return;

        try {
            setLoading(true); // Désactiver le bouton pendant l'envoi
            if (id) {
                await updateStudent(id, newStudent);
                navigator('/students');
            } else {
                if (!userId) {
                    alert("ID Utilisateur manquant pour la création.");
                    return;
                }
                await createStudent(userId, newStudent);
                navigator('/students');
            }
        } catch (error) {
            console.error('Erreur lors de la soumission : ', error);
            alert("Une erreur est survenue lors de l'enregistrement.");
        } finally {
            setLoading(false);
        }
    };

    if (loading && id) return <div className='text-center my-5'>Chargement....</div>;

    return (
        <div className='container my-4'>
            <h2 className='text-center mb-4'>
                {id ? "Modifier l'étudiant" : "Créer un nouvel étudiant"}
            </h2>

            {userId && !id && (
                <div className="alert alert-info">
                    Création d'un profil étudiant pour l'utilisateur ID : <strong>{userId}</strong>
                </div>
            )}

            <form className='border p-4 rounded shadow-sm bg-light' onSubmit={handleSubmit}>
                <div className="row">
                    <div className="col-md-6 mb-3">
                        <label className="form-label">Code Étudiant</label>
                        <input
                            type="text"
                            className={`form-control ${errors.studentCode ? 'is-invalid' : ''}`}
                            name="studentCode"
                            value={newStudent.studentCode}
                            onChange={handleChange}
                        />
                        {errors.studentCode && <div className="invalid-feedback">{errors.studentCode}</div>}
                    </div>

                    <div className="col-md-6 mb-3">
                        <label className="form-label">Niveau (Level)</label>
                        <input
                            type="text"
                            className={`form-control ${errors.level ? 'is-invalid' : ''}`}
                            name="level"
                            value={newStudent.level}
                            onChange={handleChange}
                        />
                        {errors.level && <div className="invalid-feedback">{errors.level}</div>}
                    </div>
                </div>

                <div className="d-flex justify-content-end gap-2">
                    <button type="button" onClick={() => navigator('/students')} className="btn btn-outline-secondary">
                        Annuler
                    </button>
                    <button type="submit" className="btn btn-primary" disabled={loading}>
                        {loading ? "En cours..." : (id ? "Enregistrer" : "Créer")}
                    </button>
                </div>
            </form>
        </div>
    );
};

export default NewStudentComponent;
