// ima-standalone/src/app/components/forms/teacher/new-teacher.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { TeacherService } from '../../../services/teacher/teacher-service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-new-teacher.component',
  imports: [
    CommonModule,
    ReactiveFormsModule,
  ],
  templateUrl: './new-teacher.component.html',
  styleUrl: './new-teacher.component.css',
})
export class NewTeacherComponent implements OnInit {
    teacherForm: FormGroup;
    id: string | null = null;
    userId: string | null = null;
    loading = false;

    constructor(
        private fb: FormBuilder,
        private route: ActivatedRoute,
        public router: Router,
        private teacherService: TeacherService
    ) {
        // Initialisation du formulaire avec validations
        this.teacherForm = this.fb.group({
        department: ['', Validators.required],
        grade: ['', Validators.required],
        specialty: ['', Validators.required],
        userId: ['']
        });
    }

    ngOnInit(): void {
        // Récupération des paramètres de l'URL
        this.id = this.route.snapshot.paramMap.get('id');
        this.userId = this.route.snapshot.paramMap.get('userId');

        if (this.userId) {
        this.teacherForm.patchValue({ userId: this.userId });
        }

        if (this.id) {
        this.loadTeacher();
        }
    }

    loadTeacher(): void {
        this.loading = true;
        this.teacherService.getTeacher(Number(this.id)).subscribe({
            next: async(response:any) => {
                let data = response;

                if(response instanceof Blob){
                    const text = await response.text();
                    data = JSON.parse(text);
                }

                this.teacherForm.patchValue({
                department: data.department,
                grade: data.grade,
                specialty: data.specialty,
                userId: data.userId || this.userId
                });
                this.loading = false;
            },
            error: (err) => {
                console.error("Erreur chargement enseignant", err);
                alert("Erreur lors de la récupération des données.");
                this.loading = false;
            }
        });
    }

    onSubmit(): void {
        if (this.teacherForm.invalid) {
        this.teacherForm.markAllAsTouched();
        return;
        }

        this.loading = true;
        const payload = this.teacherForm.value;

        if (this.id) {
        // Cas de la mise à jour
        this.teacherService.updateTeacher(Number(this.id), payload).subscribe({
            next: () => this.handleSuccess(),
            error: (err) => this.handleError(err)
        });
        } else {
        // Cas de la création (nécessite userId)
        if (!this.userId) {
            alert("ID Utilisateur manquant.");
            this.loading = false;
            return;
        }
        this.teacherService.createTeacher(Number(this.userId), payload).subscribe({
            next: () => this.handleSuccess(),
            error: (err) => this.handleError(err)
        });
        }
    }

    private handleSuccess(): void {
        this.loading = false;
        this.router.navigate(['/teachers']);
    }

    private handleError(err: any): void {
        console.error('Erreur lors de la soumission :', err);
        alert("Une erreur est survenue lors de l'enregistrement.");
        this.loading = false;
    }
}

<div class="container my-4">
    <h2 class="text-center mb-4">
        {{ id ? "Modifier l'enseignant" : "Créer un nouvel enseignant" }}
    </h2>

    <div *ngIf="userId && !id" class="alert alert-info">
        Profil enseignant pour l'utilisateur : <strong>{{ userId }}</strong>
    </div>

    <div *ngIf="loading && id" class="text-center my-5">
        <div class="spinner-border text-primary" role="status"></div>
        <p>Chargement...</p>
    </div>

    <form *ngIf="!(loading && id)"
        [formGroup]="teacherForm" (ngSubmit)="onSubmit()"
        class="border p-4 rounded shadow-sm bg-light"
        >
        <div class="row">
            <div class="col-md-6 mb-3">
                <label class="form-label">Département</label>
                <input type="text" class="form-control" formControlName="department"
                    [class.is-invalid]="teacherForm.get('department')?.touched && teacherForm.get('department')?.invalid">
                <div class="invalid-feedback">Le département est obligatoire</div>
            </div>

            <div class="col-md-6 mb-3">
                <label class="form-label">Grade</label>
                <input type="text" class="form-control" formControlName="grade"
                    [class.is-invalid]="teacherForm.get('grade')?.touched && teacherForm.get('grade')?.invalid">
                <div class="invalid-feedback">Le grade est obligatoire</div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 mb-3">
                <label class="form-label">Spécialité</label>
                <input type="text" class="form-control" formControlName="specialty"
                    [class.is-invalid]="teacherForm.get('specialty')?.touched && teacherForm.get('specialty')?.invalid">
                <div class="invalid-feedback">La spécialité est obligatoire</div>
            </div>
        </div>

        <div class="d-flex justify-content-end gap-2 mt-3">
            <button type="button"
                (click)="router.navigate(['/teachers'])" class="btn btn-outline-secondary">
                Annuler
            </button>
            <button type="submit" class="btn btn-primary" [disabled]="loading">
                {{ loading ? "Enregistrement..." : (id ? "Enregistrer les modifications" : "Créer l'enseignant") }}
            </button>
        </div>
    </form>
</div>

// ima-frontend-react/src/components/NewTeacherComponent.jsx
import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { createTeacher, getTeacher, updateTeacher } from '../services/TeacherService';

const NewTeacherComponent = () => {
    const { id, userId } = useParams();
    const navigator = useNavigate();

    const [newTeacher, setNewTeacher] = useState({       
        department: "",
        grade: "",
        specialty: "",
        userId: userId || ""
    });

    const [loading, setLoading] = useState(false);
    const [errors, setErrors] = useState({});

    useEffect(() => {
        if (!id) return;

        const fetchTeacher = async () => {
            try {
                setLoading(true);
                const response = await getTeacher(id);
                const data = response.data;

                setNewTeacher({
                    department: data.department || "",
                    grade: data.grade || "",
                    specialty: data.specialty || "",
                    userId: userId || data.userId || ""
                });
            } catch (error) {
                console.error("Erreur chargement enseignant", error);
                alert("Erreur lors de la récupération des données.");
            } finally {
                setLoading(false);
            }
        };

        fetchTeacher();
    }, [id, userId]);

    const handleChange = (e) => {
        const { name, value } = e.target;
        setNewTeacher(prev => ({ ...prev, [name]: value }));

        if (errors[name]) {
            setErrors(prev => ({ ...prev, [name]: null }));
        }
    };

    const validateForm = () => {
        const validationErrors = {};
        if (!newTeacher.department.trim()) validationErrors.department = 'Le département est obligatoire';
        if (!newTeacher.grade.trim()) validationErrors.grade = 'Le grade est obligatoire';
        if (!newTeacher.specialty.trim()) validationErrors.specialty = 'La spécialité est obligatoire';

        setErrors(validationErrors);
        return Object.keys(validationErrors).length === 0;
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!validateForm()) return;

        try {
            setLoading(true);
            if (id) {
                await updateTeacher(id, newTeacher);
                navigator('/teachers');
            } else {
                if (!userId) {
                    alert("ID Utilisateur manquant.");
                    return;
                }
                await createTeacher(userId, newTeacher);
                navigator('/teachers');
            }
        } catch (error) {
            console.error('Erreur lors de la soumission :', error);
            alert("Une erreur est survenue lors de l'enregistrement.");
        } finally {
            setLoading(false);
        }
    };

    if (loading && id) return <div className="text-center my-5">Chargement...</div>;

    return (
        <div className='container my-4'>
            <h2 className="text-center mb-4">
                {id ? "Modifier l'enseignant" : "Créer un nouvel enseignant"}
            </h2>
            
            {userId && !id && (
                <div className="alert alert-info">
                    Profil enseignant pour l'utilisateur : <strong>{userId}</strong>
                </div>
            )}

            <form onSubmit={handleSubmit} className="border p-4 rounded shadow-sm bg-light">
                <div className="row">
                    {/* Department */}
                    <div className="col-md-6 mb-3">
                        <label className="form-label">Département</label>
                        <input
                            type="text"
                            className={`form-control ${errors.department ? 'is-invalid' : ''}`}
                            name="department"
                            value={newTeacher.department}
                            onChange={handleChange}
                        />
                        {errors.department && <div className="invalid-feedback">{errors.department}</div>}
                    </div>

                    {/* Grade */}
                    <div className="col-md-6 mb-3">
                        <label className="form-label">Grade</label>
                        <input
                            type="text"
                            className={`form-control ${errors.grade ? 'is-invalid' : ''}`}
                            name="grade"
                            value={newTeacher.grade}
                            onChange={handleChange}
                        />
                        {errors.grade && <div className="invalid-feedback">{errors.grade}</div>}
                    </div>
                </div>

                <div className="row">
                    {/* Specialty */}
                    <div className="col-md-12 mb-3">
                        <label className="form-label">Spécialité</label>
                        <input
                            type="text"
                            className={`form-control ${errors.specialty ? 'is-invalid' : ''}`}
                            name="specialty"
                            value={newTeacher.specialty}
                            onChange={handleChange}
                        />
                        {errors.specialty && <div className="invalid-feedback">{errors.specialty}</div>}
                    </div>
                </div>

                <div className="d-flex justify-content-end gap-2 mt-3">
                    <button type="button" onClick={() => navigator('/teachers')} className="btn btn-outline-secondary">
                        Annuler
                    </button>
                    <button type="submit" className="btn btn-primary" disabled={loading}>
                        {loading ? "Enregistrement..." : (id ? "Enregistrer les modifications" : "Créer l'enseignant")}
                    </button>
                </div>
            </form>
        </div>
    );
}

export default NewTeacherComponent;
