// ima-standalone/src/app/components/forms/user/new-user.component.ts
import { Component, OnInit } from '@angular/core';
import { FormArray, FormBuilder, FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { UserService } from '../../../services/user/user-service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-new-user.component',
  imports: [
    CommonModule,
    ReactiveFormsModule,
  ],
  templateUrl: './new-user.component.html',
  styleUrl: './new-user.component.css',
})
export class NewUserComponent implements OnInit {

    userForm: FormGroup;
    userId: string | null = null;
    loading = false;

    ROLE_LIST = [
        { id: 'ADMIN', name: 'Administrateur' },
        { id: 'TEACHER', name: 'Enseignant' },
        { id: 'STUDENT', name: 'Étudiant' },
        { id: 'COMPANY', name: 'Entreprise' },
        { id: 'USER', name: 'Utilisateur' },
    ];

    constructor(
        private fb: FormBuilder,
        private route: ActivatedRoute,
        private router: Router,
        private userService: UserService
    ) {
        // Initialisation du formulaire
        this.userForm = this.fb.group({
            firstName: ['', Validators.required],
            lastName: ['', Validators.required],
            email: ['', [Validators.required, Validators.email]],
            password: [''], // Validateur conditionnel ajouté dans ngOnInit
            telephone: ['', Validators.required],
            roles: this.fb.array([], Validators.required)
        });
    }

    ngOnInit(): void {
        this.userId = this.route.snapshot.paramMap.get('id');

        // Gestion du mot de passe requis seulement à la création
        if (!this.userId) {
            this.userForm.get('password')?.setValidators([Validators.required]);
        }

        if (this.userId) {
            this.loadUser();
        }
    }

    // --- Gestion des Rôles (Checkboxes) ---
    onRoleChange(event: any) {
        const roles: FormArray = this.userForm.get('roles') as FormArray;
        if (event.target.checked) {
            roles.push(new FormControl(event.target.value));
        } else {
            const index = roles.controls.findIndex(x => x.value === event.target.value);
            roles.removeAt(index);
        }
    }

    isRoleChecked(roleId: string): boolean {
        return (this.userForm.get('roles') as FormArray).value.includes(roleId);
    }

    // --- Actions ---
    loadUser() {
        this.loading = true;
        const idAsNumber = Number(this.userId);

        this.userService.getUserById(idAsNumber!).subscribe({
            next: async(response: any) => {

                let user = response;

                if(response instanceof Blob){
                    const text = await response.text();
                    user = JSON.parse(text);
                }

                const rolesFromApi = user.roles || [];
                // Transformation des rôles comme dans le code React
                const formattedRoles = rolesFromApi.map((role: any) => {
                    if (typeof role === 'string') return role;
                    return role.id || role.name?.replace("ROLE_", "");
                }).filter(Boolean);

                this.userForm.patchValue({ ...user, password: '' });

                // Remplissage du FormArray des rôles
                const rolesArray = this.userForm.get('roles') as FormArray;
                formattedRoles.forEach((role: string) => rolesArray.push(new FormControl(role)));

                this.loading = false;
            },
            error: (err) => {
                console.error(err);
                this.loading = false;
            }
        });
    }

    onSubmit() {
        if (this.userForm.invalid) {
            this.userForm.markAllAsTouched();
            return;
        }

        const payload = {
            ...this.userForm.value,
            roles: this.userForm.value.roles.map((r: string) => r.toUpperCase())
        };

        if (this.userId) {
            // Ligne 114 : Conversion en number car le service l'exige
            this.userService.updateUser(Number(this.userId), payload).subscribe({
                next: () => this.router.navigate(['/users']),
                error: (err) => console.error(err)
            });
        } else {
            // Création
            this.userService.createUser(payload).subscribe({
                next: (response) => {
                    // Ligne 121 : Sécurisation de l'ID (en string) et des rôles (par défaut [])
                    const createdId = String(response.id);
                    const roles = response.roles || []; // Évite le 'undefined'
                    this.redirectAfterCreation(createdId, roles);
                },
                error: (err) => console.error(err)
            });
        }
    }

    private redirectAfterCreation(id: string, roles: string[]) {
        if (roles.includes('STUDENT')) this.router.navigate(['/students/new', id]);
        else if (roles.includes('TEACHER')) this.router.navigate(['/teachers/new', id]);
        else if (roles.includes('COMPANY')) this.router.navigate(['/companies/new', id]);
        else this.router.navigate(['/users']);
    }

    cancel() {
        this.router.navigate(['/users']);
    }

}

<div class="container my-4">
    <h2 class="text-center mb-4">
        {{ userId ? "Modifier l'utilisateur" : "Créer un nouvel utilisateur" }}
    </h2>

    <div *ngIf="loading" class="text-center my-5">Chargement...</div>

    <form *ngIf="!loading" [formGroup]="userForm" (ngSubmit)="onSubmit()" class="border p-4 rounded shadow-sm bg-light">
        <div class="row">
            <div class="col-md-6 mb-3">
                <label class="form-label">Prénom</label>
                <input type="text" class="form-control" formControlName="firstName"
                    [class.is-invalid]="userForm.get('firstName')?.touched && userForm.get('firstName')?.invalid">
                <div class="invalid-feedback">Prénom requis</div>
            </div>

            <div class="col-md-6 mb-3">
                <label class="form-label">Nom</label>
                <input type="text" class="form-control" formControlName="lastName"
                    [class.is-invalid]="userForm.get('lastName')?.touched && userForm.get('lastName')?.invalid">
                <div class="invalid-feedback">Nom requis</div>
            </div>
        </div>

        <div class="mb-3">
            <label class="form-label">Email</label>
            <input type="email" class="form-control" formControlName="email"
                    [class.is-invalid]="userForm.get('email')?.touched && userForm.get('email')?.invalid">
            <div class="invalid-feedback">Email valide requis</div>
        </div>

        <div class="mb-3" *ngIf="!userId">
            <label class="form-label">Mot de passe</label>
            <input type="password" class="form-control" formControlName="password"
                    [class.is-invalid]="userForm.get('password')?.touched && userForm.get('password')?.invalid">
            <div class="invalid-feedback">Mot de passe requis</div>
        </div>

        <div class="mb-3">
            <label class="form-label">Téléphone</label>
            <input type="tel" class="form-control" formControlName="telephone"
                    [class.is-invalid]="userForm.get('telephone')?.touched && userForm.get('telephone')?.invalid">
        </div>

        <div class="mb-4">
            <label class="form-label d-block">Rôles attribués</label>
            <div class="d-flex flex-wrap gap-3">
                <div *ngFor="let role of ROLE_LIST" class="form-check">
                    <input type="checkbox"
                        class="form-check-input"
                        [id]="'role-' + role.id"
                        [value]="role.id"
                        [checked]="isRoleChecked(role.id)"
                        (change)='onRoleChange($event)'>

                    <label class="form-check-label" [for]="'role-' + role.id">
                        {{ role.name }}
                    </label>
                </div>
            </div>
            <div *ngIf="userForm.get('roles')?.touched && userForm.get('roles')?.invalid" class="text-danger small mt-1">
                Au moins un rôle requis
            </div>
        </div>

        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <button type="button" (click)="cancel()"
                class="btn btn-outline-secondary">
                Annuler
            </button>
            <button type="submit" class="btn btn-primary" [disabled]="loading">
                {{ userId ? "Enregistrer les modifications" : "Créer l'utilisateur" }}
            </button>
        </div>
    </form>
</div>

// ima-frontend-react/src/components/NewUserComponent.jsx
import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { createUser, getUser, updateUser } from '../services/UserService';

const NewUserComponent = () => {
    const { id } = useParams(); 
    const navigator = useNavigate();

    const ROLE_LIST = [
        { id: 'ADMIN', name: 'Administrateur' },
        { id: 'TEACHER', name: 'Enseignant' },
        { id: 'STUDENT', name: 'Étudiant' },
        { id: 'COMPANY', name: 'Entreprise' },
        { id: 'USER', name: 'Utilisateur' },
    ];

    const [newUser, setNewUser] = useState({
        firstName: "",
        lastName: "",
        email: "",
        password: "",
        telephone: "",
        roles: []
    });

    const [loading, setLoading] = useState(false);
    const [errors, setErrors] = useState({});

    // --- 1. Chargement des données au montage ---
    useEffect(() => {
        if (id) {        
            getUser(id)
                .then((response) => {
                    const fetchedUser = response.data;
                    // Transformation des rôles : on ne garde que les IDs pour les checkboxes
                    if (Array.isArray(fetchedUser.roles)) {
                        fetchedUser.roles = fetchedUser.roles.map(role => {
                            if (typeof role === 'string') return role;
                            if (typeof role === 'object') {
                                return role.id || role.name?.replace("ROLE_", "");
                            }
                            return null;
                        }).filter(Boolean);
                    }

                    // On garde le mot de passe vide à l'édition pour ne pas écraser l'existant par erreur
                    setNewUser({ ...fetchedUser, password: "" });
                })
                .catch(error => {
                    console.error("Erreur chargement utilisateur:", error);
                })
                .finally(() => setLoading(false));
        }
    }, [id]);

    // --- 2. Gestionnaires d'événements ---
    const handleChange = (e) => {
        const { name, value } = e.target;
        setNewUser(prev => ({ ...prev, [name]: value }));
    };

    const handleRoleChange = (roleId) => {
        setNewUser(prev => {
            const isSelected = prev.roles.includes(roleId);
            const updatedRoles = isSelected
                ? prev.roles.filter(id => id !== roleId) // Retirer
                : [...prev.roles, roleId]; // Ajouter
            return { ...prev, roles: updatedRoles };
        });
    };

    const validateForm = () => {
        const errors = {};
        if (!newUser.firstName.trim()) errors.firstName = 'Prénom requis';
        if (!newUser.lastName.trim()) errors.lastName = 'Nom requis';
        if (!newUser.email.trim()) errors.email = 'Email requis';
        // Mot de passe requis uniquement à la création
        if (!id && !newUser.password.trim()) errors.password = 'Mot de passe requis';
        if (!newUser.telephone.trim()) errors.telephone = 'Téléphone requis';
        if (newUser.roles.length === 0) errors.roles = 'Au moins un rôle requis';

        setErrors(errors);
        return Object.keys(errors).length === 0;
    };

    const redirectAfterCreation = (userId, roles) => {
        if (roles.includes('STUDENT')) {
            navigator(`/students/new/${userId}`);
        } else if (roles.includes('TEACHER')) {
            navigator(`/teachers/new/${userId}`);
        } else if (roles.includes('COMPANY')) {
            navigator(`/companies/new/${userId}`);
        } else {
            navigator('/users'); // fallback
        }
    };

    const payload = {
        ...newUser,
        roles: newUser.roles.map(r => r.toUpperCase())
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!validateForm()) return;

        try {
            if (id) {
                // UPDATE
                await updateUser(id, payload);
                
                console.log("Utilisateur mis à jour");
            } else {
                // CREATE
                const response = await createUser(payload);
                const createdUser = response.data;

                redirectAfterCreation(createdUser.id, createdUser.roles);
                console.log("Utilisateur créé");
            } 
            navigator('/users');          
        } catch (error) {
            console.error("Erreur lors de la soumission :", error);
        }
    };

    if (loading) return <div className="text-center my-5">Chargement...</div>;

    return (
        <div className="container my-4">
            <h2 className="text-center mb-4">
                {id ? "Modifier l'utilisateur" : "Créer un nouvel utilisateur"}
            </h2>

            <form onSubmit={handleSubmit} className="border p-4 rounded shadow-sm bg-light">
                <div className="row">
                    <div className="col-md-6 mb-3">
                        <label className="form-label">Prénom</label>
                        <input
                            type="text"
                            className={`form-control ${errors.firstName ? 'is-invalid' : ''}`}
                            name="firstName"
                            value={newUser.firstName}
                            onChange={handleChange}
                        />
                        {errors.firstName && <div className="invalid-feedback">{errors.firstName}</div>}
                    </div>
                    <div className="col-md-6 mb-3">
                        <label htmlFor="lastName" className="form-label">Nom</label>
                        <input
                            type="text"
                            className="form-control"
                            id="lastName"
                            name="lastName"
                            value={newUser.lastName}
                            onChange={handleChange}
                            required
                        />
                        {errors.lastName && <div className="text-danger">{errors.lastName}</div>}
                    </div>
                </div>

                <div className="mb-3">
                    <label htmlFor="email" className="form-label">Email</label>
                    <input
                        type="email"
                        className="form-control"
                        id="email"
                        name="email"
                        value={newUser.email}
                        onChange={handleChange}
                        required
                    />
                    {errors.email && <div className="text-danger">{errors.email}</div>}
                </div>

                {!id && (
                    <div className="mb-3">
                        <label htmlFor="password" className="form-label">Mot de passe</label>
                        <input
                            type="password"
                            className="form-control"
                            id="password"
                            name="password"
                            value={newUser.password}
                            onChange={handleChange}
                            required
                        />
                        {errors.password && <div className="text-danger">{errors.password}</div>}
                    </div>
                )}


                <div className="mb-3">
                    <label className="form-label">Téléphone</label>
                    <input
                        type="tel"
                        className={`form-control ${errors.telephone ? 'is-invalid' : ''}`}
                        name="telephone"
                        value={newUser.telephone}
                        onChange={handleChange}
                    />
                </div>

                <div className="mb-4">
                    <label className="form-label d-block">Rôles attribués</label>
                    <div className="d-flex flex-wrap gap-3">
                        {ROLE_LIST.map(role => (
                            <div key={role.id} className="form-check">
                                <input
                                    type="checkbox"
                                    className="form-check-input"
                                    id={`role-${role.id}`}
                                    checked={newUser.roles.includes(role.id)}
                                    onChange={() => handleRoleChange(role.id)}
                                />
                                <label className="form-check-label" htmlFor={`role-${role.id}`}>
                                    {role.name}
                                </label>
                            </div>
                        ))}
                    </div>
                    {errors.roles && <div className="text-danger small mt-1">{errors.roles}</div>}
                </div>

                <div className="d-grid gap-2 d-md-flex justify-content-md-end">
                    <button type="button" onClick={() => navigator('/users')} className="btn btn-outline-secondary">
                        Annuler
                    </button>
                    <button type="submit" className="btn btn-primary" disabled={loading} >
                        {id ? "Enregistrer les modifications" : "Créer l'utilisateur"}
                    </button>
                </div>
            </form>
        </div>
    );
};

export default NewUserComponent;
