// ima-frontend-react/src/components/NewInternshipComponent.jsx
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { createInternship } from '../services/InternshipService'; 
import { listCompanies } from '../services/CompanyService';

const NewInternshipComponent = () => {

    const [companies, setCompanies] = useState([]);

    const navigator = useNavigate();
    const [newInternship, setNewInternship] = useState({
        title: '',
        description: '',
        city: '',
        country: '',
        startDate: '',
        endDate: '',
        isActive: true,
        isPaid: true,
        company: { id: '' } // On stocke généralement l'ID de l'entreprise sélectionnée
    });

    // 1. Charger les entreprises au montage du composant
    useEffect(() => {
        const fetchCompanies = async () => {
            try {
                const response = await listCompanies();
                setCompanies(response.data);
            } catch (error) {
                console.error("Erreur lors du chargement des entreprises", error);
            }
        };
        fetchCompanies();
    }, []);

    const handleChange = (e) => {
        const { name, value, type, checked } = e.target;
        
        // 2. Gestion spécifique pour l'ID de l'entreprise
        if (name === "companyId") {
            setNewInternship({ 
                ...newInternship, 
                company: { id: value } 
            });
        } else {
            setNewInternship({
                ...newInternship,
                [name]: type === 'checkbox' ? checked : value
            });
        }
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            console.log("Envoi des données:", newInternship);
            await createInternship(newInternship);
            navigator('/internships');
        } catch (error) {
            console.error("Erreur lors de la création", error);
        }
    };

    return (
        <div className="container mt-5">
            <div className="card shadow">
                <div className="card-header bg-primary text-white">
                    <h3 className="mb-0">Publier une offre de stage</h3>
                </div>

                <div className="mb-3">
                    <label className="form-label fw-bold text-primary">Entreprise partenaire</label>
                    <select 
                        name="companyId" 
                        className="form-select" 
                        value={newInternship.company.id} 
                        onChange={handleChange}
                        required
                    >
                        <option value="">-- Sélectionner une entreprise --</option>
                        {companies.map(company => (
                            <option key={company.id} value={company.id}>
                                {company.name} ({company.city})
                            </option>
                        ))}
                    </select>
                    <div className="form-text">L'entreprise doit être déjà enregistrée dans le système.</div>
                </div>

                <div className="card-body">
                    <form onSubmit={handleSubmit}>
                        <div className="row">
                            <div className="col-md-12 mb-3">
                                <label className="form-label">Titre du stage</label>
                                <input type="text" name="title" className="form-control" 
                                    value={newInternship.title} onChange={handleChange} required />
                            </div>
                            
                            <div className="col-md-6 mb-3">
                                <label className="form-label">Ville</label>
                                <input type="text" name="city" className="form-control" 
                                    value={newInternship.city} onChange={handleChange} required />
                            </div>

                            <div className="col-md-6 mb-3">
                                <label className="form-label">Pays</label>
                                <input type="text" name="country" className="form-control" 
                                    value={newInternship.country} onChange={handleChange} required />
                            </div>

                            <div className="col-md-6 mb-3">
                                <label className="form-label">Date de début</label>
                                <input type="date" name="startDate" className="form-control" 
                                    value={newInternship.startDate} onChange={handleChange} required />
                            </div>

                            <div className="col-md-6 mb-3">
                                <label className="form-label">Date de fin</label>
                                <input type="date" name="endDate" className="form-control" 
                                    value={newInternship.endDate} onChange={handleChange} required />
                            </div>

                            <div className="col-md-12 mb-3">
                                <label className="form-label">Description</label>
                                <textarea name="description" className="form-control" rows="4"
                                    value={newInternship.description} onChange={handleChange}></textarea>
                            </div>

                            <div className="col-md-12 mb-3 d-flex gap-4">
                                <div className="form-check">
                                    <input type="checkbox" name="isPaid" className="form-check-input" id="isPaid"
                                        checked={newInternship.isPaid} onChange={handleChange} />
                                    <label className="form-check-label" htmlFor="isPaid">Stage rémunéré</label>
                                </div>
                                <div className="form-check">
                                    <input type="checkbox" name="isActive" className="form-check-input" id="isActive"
                                        checked={newInternship.isActive} onChange={handleChange} />
                                    <label className="form-check-label" htmlFor="isActive">Activer l'offre</label>
                                </div>
                            </div>
                        </div>

                        <div className="text-end mt-4">
                            <button type="button" className="btn btn-secondary me-2" onClick={() => navigator(-1)}>Annuler</button>
                            <button type="submit" className="btn btn-success px-4">Enregistrer le stage</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    );
};

export default NewInternshipComponent;

// ima-standalone/src/app/components/forms/internship/new-internship.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { InternshipService } from '../../../services/internship/internship-service';
import { CompanyService } from '../../../services/company/company-service';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-new-internship',
  imports: [
    CommonModule,
    ReactiveFormsModule,
  ],
  templateUrl: './new-internship.component.html',
  styleUrl: './new-internship.component.css',
})
export class NewInternshipComponent implements OnInit {
    internshipForm: FormGroup;
    companies: any[] = [];
    loading = false;

    constructor(
        private fb: FormBuilder,
        private internshipService: InternshipService,
        private companyService: CompanyService,
        public router: Router
    ) {
        // Structure du formulaire avec objet imbriqué pour la compagnie
        this.internshipForm = this.fb.group({
        title: ['', Validators.required],
        description: ['', Validators.required],
        city: ['', Validators.required],
        country: ['', Validators.required],
        startDate: ['', Validators.required],
        endDate: ['', Validators.required],
        isActive: [true],
        isPaid: [true],
        company: this.fb.group({
            id: ['', Validators.required]
        })
        });
    }

    ngOnInit(): void {
        this.loadCompanies();
    }

    loadCompanies(): void {
        this.companyService.getAllCompanies().subscribe({
            next: async(response: any) => {

                let data = response;

                // Si c'est un Blob, on doit le convertir en texte puis en JSON
                if (response instanceof Blob) {
                    const text = await response.text();
                    data = JSON.parse(text);
                }

                // Une fois converti, on applique la logique de vérification
                if(Array.isArray(data)){
                    this.companies = data;
                }else if (data && Array.isArray(data.body)) {
                    this.companies = data.body;
                } else {
                    this.companies = [];
                }
                this.loading = false;

            },
            error: (err) => console.error("Erreur chargement entreprises", err)
        });
    }

    onSubmit(): void {
        if (this.internshipForm.invalid) {
            this.internshipForm.markAllAsTouched();
            return;
        }

        this.loading = true;
        this.internshipService.createInternship(this.internshipForm.value).subscribe({
            next: () => {
                this.loading = false;
                this.router.navigate(['/internships']);
            },
            error: (err) => {
                this.loading = false;
                console.error("Erreur création stage", err);
            }
        });
    }
}

<div class="container mt-5">
    <div class="card shadow">
        <div class="card-header bg-primary text-white">
        <h3 class="mb-0">Publier une offre de stage</h3>
        </div>

        <div class="card-body">
            <form [formGroup]="internshipForm" (ngSubmit)="onSubmit()">

                <div class="mb-3" formGroupName="company">
                    <label class="form-label fw-bold text-primary">Entreprise partenaire</label>
                    <select formControlName="id" class="form-select"
                            [class.is-invalid]="internshipForm.get('company.id')?.touched && internshipForm.get('company.id')?.invalid">
                        <option value="">-- Sélectionner une entreprise --</option>
                        <option *ngFor="let company of companies" [value]="company.id">
                        {{ company.name }} ({{ company.city }})
                        </option>
                    </select>
                    <div class="invalid-feedback">Veuillez sélectionner une entreprise.</div>
                    <div class="form-text">L'entreprise doit être déjà enregistrée dans le système.</div>
                </div>

                <div class="row">
                    <div class="col-md-12 mb-3">
                        <label class="form-label">Titre du stage</label>
                        <input type="text" class="form-control" formControlName="title"
                            [class.is-invalid]="internshipForm.get('title')?.touched && internshipForm.get('title')?.invalid">
                    </div>

                    <div class="col-md-6 mb-3">
                        <label class="form-label">Ville</label>
                        <input type="text" class="form-control" formControlName="city"
                            [class.is-invalid]="internshipForm.get('city')?.touched && internshipForm.get('city')?.invalid">
                    </div>

                    <div class="col-md-6 mb-3">
                        <label class="form-label">Pays</label>
                        <input type="text" class="form-control" formControlName="country"
                            [class.is-invalid]="internshipForm.get('country')?.touched && internshipForm.get('country')?.invalid">
                    </div>

                    <div class="col-md-6 mb-3">
                        <label class="form-label">Date de début</label>
                        <input type="date" class="form-control" formControlName="startDate"
                            [class.is-invalid]="internshipForm.get('startDate')?.touched && internshipForm.get('startDate')?.invalid">
                    </div>

                    <div class="col-md-6 mb-3">
                        <label class="form-label">Date de fin</label>
                        <input type="date" class="form-control" formControlName="endDate"
                            [class.is-invalid]="internshipForm.get('endDate')?.touched && internshipForm.get('endDate')?.invalid">
                    </div>

                    <div class="col-md-12 mb-3">
                        <label class="form-label">Description</label>
                        <textarea class="form-control" rows="4" formControlName="description"
                                [class.is-invalid]="internshipForm.get('description')?.touched && internshipForm.get('description')?.invalid"></textarea>
                    </div>

                    <div class="col-md-12 mb-3 d-flex gap-4">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="isPaid" formControlName="isPaid">
                            <label class="form-check-label" htmlFor="isPaid">Stage rémunéré</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="isActive" formControlName="isActive">
                            <label class="form-check-label" htmlFor="isActive">Activer l'offre</label>
                        </div>
                    </div>
                </div>

                <div class="text-end mt-4">
                    <button type="button" class="btn btn-secondary me-2" (click)="router.navigate(['/internships'])">
                        Annuler
                    </button>
                    <button type="submit" class="btn btn-success px-4" [disabled]="loading">
                        {{ loading ? 'Enregistrement...' : 'Enregistrer le stage' }}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
